// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbrbwsdjtiwveeemcphv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFicmJ3c2RqdGl3dmVlZW1jcGh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMjQxMzIsImV4cCI6MjA2MTgwMDEzMn0.0kD7g0pJJFqpeo6hiDIxoV6KXG-MVP3Au0GaZa8af4I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);